#pragma once

#include <unordered_map>
#include <string>
#include "napi.h"

using namespace std;

namespace gamemapping
{
    struct GAME_NAME_MAP
    {
        string codeName;
        string gameName;
    } const GAME_NAME_MAPS[] = {
        {"agent", "Battle.net Agent"},
        {"agent_beta", "Battle.net Agent Beta"},
        {"agent_test", "Battle.net Agent Test"},
        {"bna", "Battle.net Launcher"},
        {"bts", "Bootstrapper"},
        {"catalogs", "Game Catalog"},
        {"clnt", "Client"},
        {"rtro", "Blizzard Arcade Collection"},
        {"rtrob", "Blizzard Arcade Collection Beta"},
        {"rtrodev", "Blizzard Arcade Collection Development Region"},
        {"rtrot", "Blizzard Arcade Collection Public Test Realm"},
        {"bnt", "Heroes of the Storm Alpha"},
        {"hero", "Heroes of the Storm"},
        {"heroc", "Heroes of the Storm Tournament Realm"},
        {"herot", "Heroes of the Storm Public Test Realm"},
        {"s1", "StarCraft"},
        {"s1a", "StarCraft 1 Alpha"},
        {"s1t", "StarCraft Public Test Realm"},
        {"s2", "StarCraft II"},
        {"s2b", "StarCraft II Beta"},
        {"s2t", "StarCraft II Public Test Realm"},
        {"sc2", "StarCraft II"},
        {"w2bn", "WarCraft II: Battle.net Edition"},
        {"w3", "Warcraft III"},
        {"w3b", "Warcraft III: Reforged Beta"},
        {"w3d", "Warcraft III Public Test Realm (Internal)"},
        {"w3t", "Warcraft III Public Test Realm"},
        {"war3", "Warcraft III (old)"},
        {"wow", "World of Warcraft"},
        {"wow_beta", "World of Warcraft Shadowlands Beta"},
        {"wow_classic", "World of Warcraft Cataclysm Classic"},
        {"wow_classic_beta", "World of Warcraft Wrath of the Lich King"},
        {"wow_classic_era", "World of Warcraft Classic"},
        {"wow_classic_era_beta", "World of Warcraft Classic Beta"},
        {"wow_classic_era_ptr", "World of Warcraft PTR"},
        {"wow_classic_ptr", "World of Warcraft Wrath of the Lich King Classic PTR"},
        {"wowdemo", "World of Warcraft (Classic) Demo"},
        {"wowdev", "World of Warcraft Mainline Internal Test Development Region"},
        {"wowdev2", "World of Warcraft Classic Internal Alpha Vendor 2"},
        {"wowdev3", "World of Warcraft Development 3 Vendor 3"},
        {"wowe1", "World of Warcraft Event Realm"},
        {"wowe2", "World of Warcraft Event Realm 2"},
        {"wowe3", "World of Warcraft Event 3"},
        {"wowlivetest", "World of Warcraft Dark Realm (Deprecated)"},
        {"wowlivetest2", "World of Warcraft Dark Realm Test"},
        {"wowt", "World of Warcraft PTR"},
        {"wowv", "World of Warcraft Vendor 1"},
        {"wowv2", "World of Warcraft Vendor 2"},
        {"wowv3", "World of Warcraft Vendor 3"},
        {"wowv4", "World of Warcraft Vendor 4"},
        {"wowxptr", "World of Warcraft PTR"},
        {"wowz", "World of Warcraft Submissions"},
        {"gryphon", "Warcraft Rumble"},
        {"gryphondev", "Warcraft Rumble Tech Test Development Region"},
        {"drtl", "Diablo I"},
        {"drtl2", "Diablo I Unknown 2"},
        {"osi", "Diablo II: Resurrected"},
        {"osia", "Diablo II: Resurrected Early Review"},
        {"osib", "Diablo II: Resurrected Beta"},
        {"osidev", "Diablo II: Resurrected Development Region"},
        {"osit", "Diablo II: Resurrected Public Test Realm"},
        {"osiv1", "Diablo II: Resurrected Vendor 1"},
        {"osiv2", "Diablo II: Resurrected Vendor 2"},
        {"osiv3", "Diablo II: Resurrected Vendor 3"},
        {"osiv4", "Diablo II: Resurrected Vendor 4"},
        {"osiv5", "Diablo II: Resurrected Vendor 5"},
        {"osiv6", "Diablo II: Resurrected Vendor 6"},
        {"d3", "Diablo III"},
        {"d3b", "Diablo III Beta"},
        {"d3cn", "Diablo III China"},
        {"d3cnt", "Diablo III China Test"},
        {"d3t", "Diablo III Public Test Realm"},
        {"fenris", "Diablo IV"},
        {"fenrisb", "Diablo IV - Server Slam"},
        {"fenrisdev", "Diablo IV - Tech Alpha"},
        {"fenrisdev2", "Diablo IV Vendor 2"},
        {"fenrise", "Diablo IV Pre-Launch"},
        {"fenristest", "Diablo IV Public Test Realm"},
        {"fenrisvendor", "Diablo IV Vendor 1"},
        {"fenrisvendor2", "Diablo IV Vendor 2"},
        {"fenrisvendor3", "Diablo IV Vendor 3"},
        {"fenrisvendor4", "Diablo IV"},
        {"fenrisvendor5", "Diablo IV"},
        {"anbs", "Diablo Immortal"},
        {"anbsdev", "Diablo Immortal Development Region"},
        {"hsb", "Hearthstone"},
        {"hsc", "Hearthstone Tournament Realm"},
        {"hsdev", "Hearthstone Alpha"},
        {"hse", "Hearthstone Event Realm"},
        {"hse1", "Hearthstone Event Realm 1"},
        {"hsrc", "Hearthstone"},
        {"hst", "Hearthstone Test"},
        {"pro", "Overwatch 2"},
        {"prob", "Overwatch 2 Beta"},
        {"probv1", "Overwatch 2 BVID 1"},
        {"probv2", "Overwatch 2 BVID 2"},
        {"probv3", "Overwatch 2 BVID 3"},
        {"proc", "Overwatch 2 Tournament A"},
        {"proc2", "Overwatch 2 Tournament B"},
        {"proc2_cn", "Overwatch Tournament B China"},
        {"proc2_eu", "Overwatch Tournament B Europe"},
        {"proc2_kr", "Overwatch Tournament B Asia"},
        {"proc3", "Overwatch 2 Dev Two"},
        {"proc4", "Overwatch 2 Tournament C"},
        {"proc5", "Overwatch 2 Overwatch Esports 2"},
        {"proc_cn", "Overwatch Tournament China"},
        {"proc_eu", "Overwatch Tournament Europe"},
        {"proc_kr", "Overwatch Tournament Asia"},
        {"procr", "Overwatch 2 Overwatch League Viewer"},
        {"procr2", "Overwatch 2 Overwatch League Viewer"},
        {"prodemo", "Overwatch 2 Dev Three"},
        {"prodemo2", "Overwatch 2 Dev Four"},
        {"prodemo3", "Overwatch 2 Vendor Competitive"},
        {"prodemo4", "Overwatch 2 Preview"},
        {"prodemo5", "Overwatch 2 Preview 2"},
        {"prodev", "Overwatch 2 Dev One"},
        {"prodev6", "Overwatch 2 Dev Six Vendor 6"},
        {"prodev7", "Overwatch 2 Dev Seven Vendor 7"},
        {"prodev8", "Overwatch 2 Dev Eight Vendor 8"},
        {"prodev9", "Overwatch 2 Dev Nine Vendor 9"},
        {"prodevops", "Overwatch 2 Dev Ops 1"},
        {"prodevops2", "Overwatch 2 Dev Ops 2"},
        {"proev", "Overwatch 2 Overwatch Esports"},
        {"proindev", "Overwatch 2 Dev Five"},
        {"prolocv1", "Overwatch 2 Localization 1"},
        {"prolocv2", "Overwatch 2 Localization 2"},
        {"prolocv3", "Overwatch 2 Localization 3"},
        {"prolocv4", "Overwatch 2 Localization 4"},
        {"proms", "Overwatch 2 Overwatch World Cup 2019"},
        {"prot", "Overwatch 2 Public Test Region"},
        {"proutr", "Overwatch 2 User Test Realm"},
        {"prov", "Overwatch 2 Vendor"},
        {"provac", "Overwatch 2 Vendor AC"},
        {"provbv", "Overwatch 2 Vendor BVID"},
        {"dst2", "Destiny 2"},
        {"dst2a", "Destiny 2 Alpha"},
        {"dst2dev", "Destiny 2 \"takehome\" Dev"},
        {"dst2e1", "Destiny 2 Event"},
        {"dst2igr", "Destiny 2 Internet Game Room"},
        {"dst2t", "Destiny 2 Public Test"},
        {"auks", "Call of Duty"},
        {"auksa", "Call of Duty: Modern Warfare II Alpha"},
        {"auksb", "Call of Duty: Modern Warfare II Beta"},
        {"auksdev", "Call of Duty Dev"},
        {"aukse", "Call of Duty: Modern Warfare II Event 1"},
        {"aukse2", "Call of Duty Event 2"},
        {"auksese", "Call of Duty: Modern Warfare II E-Sports Event"},
        {"auksesp", "Call of Duty eSports Player"},
        {"auksess", "Call of Duty eSports Staff"},
        {"auksv1", "Call of Duty Vendor 1"},
        {"auksv10", "Call of Duty Vendor 10"},
        {"auksv11", "Call of Duty Vendor 11"},
        {"auksv12", "Call of Duty Vendor 12"},
        {"auksv13", "Call of Duty Vendor 13"},
        {"auksv14", "Call of Duty Vendor 14"},
        {"auksv15", "Call of Duty Vendor 15"},
        {"auksv16", "Call of Duty Vendor 16"},
        {"auksv17", "Call of Duty Vendor 17"},
        {"auksv18", "Call of Duty Vendor 18"},
        {"auksv19", "Call of Duty Vendor 19"},
        {"auksv2", "Call of Duty Vendor 2"},
        {"auksv20", "Call of Duty Vendor 20"},
        {"auksv21", "Call of Duty Vendor 21"},
        {"auksv22", "Call of Duty Vendor 22"},
        {"auksv23", "Call of Duty Vendor 23"},
        {"auksv3", "Call of Duty Vendor 3"},
        {"auksv4", "Call of Duty Vendor 4"},
        {"auksv5", "Call of Duty Vendor 5"},
        {"auksv6", "Call of Duty Vendor 6"},
        {"auksv7", "Call of Duty Vendor 7"},
        {"auksv8", "Call of Duty Vendor 8"},
        {"auksv9", "Call of Duty Vendor 9"},
        {"fore", "Call of Duty: Vanguard"},
        {"forea", "Call of Duty: Vanguard Alpha"},
        {"foreb", "Call of Duty: Vanguard Beta"},
        {"forec", "Call of Duty: Vanguard CDL Player"},
        {"forecdlstaff", "Call of Duty: Vanguard CDL Staff"},
        {"foredev", "Call of Duty: Vanguard Development Region"},
        {"forev1", "Call of Duty: Vanguard Vendor 1"},
        {"forev10", "Call of Duty: Vanguard Vendor 10"},
        {"forev11", "Call of Duty: Vanguard Vendor 11"},
        {"forev12", "Call of Duty: Vanguard Vendor 12"},
        {"forev13", "Call of Duty: Vanguard Vendor 13"},
        {"forev14", "Call of Duty: Vanguard Vendor 14"},
        {"forev15", "Call of Duty: Vanguard Vendor 15"},
        {"forev16", "Call of Duty: Vanguard Vendor 16"},
        {"forev17", "Call of Duty: Vanguard Vendor 17"},
        {"forev18", "Call of Duty: Vanguard Vendor 18"},
        {"forev19", "Call of Duty: Vanguard Vendor 19"},
        {"forev2", "Call of Duty: Vanguard Vendor 2"},
        {"forev20", "Call of Duty: Vanguard Vendor 20"},
        {"forev3", "Call of Duty: Vanguard Vendor 3"},
        {"forev4", "Call of Duty: Vanguard Vendor 4"},
        {"forev5", "Call of Duty: Vanguard Vendor 5"},
        {"forev6", "Call of Duty: Vanguard Vendor 6"},
        {"forev7", "Call of Duty: Vanguard Vendor 7"},
        {"forev8", "Call of Duty: Vanguard Vendor 8"},
        {"forev9", "Call of Duty: Vanguard Vendor 9"},
        {"odin", "Call of Duty: Modern Warfare"},
        {"odina", "Call of Duty: Warzone Alpha"},
        {"odinb", "Call of Duty: Warzone Beta"},
        {"odindev", "Call of Duty: Modern Warfare Modern Warfare Development Region"},
        {"odine", "Call of Duty: Warzone Event 1"},
        {"odinv1", "Call of Duty: Modern Warfare Modern Warfare Vendor 1"},
        {"odinv10", "Call of Duty: Modern Warfare Modern Warfare Vendor 10"},
        {"odinv11", "Call of Duty: Modern Warfare Modern Warfare Vendor 11"},
        {"odinv12", "Call of Duty: Modern Warfare Modern Warfare Vendor 12"},
        {"odinv13", "Call of Duty: Modern Warfare Modern Warfare Vendor 13"},
        {"odinv14", "Call of Duty: Modern Warfare Modern Warfare Vendor 14"},
        {"odinv15", "Call of Duty: Modern Warfare Modern Warfare Vendor 15"},
        {"odinv16", "Call of Duty: Modern Warfare Modern Warfare Vendor 16"},
        {"odinv2", "Call of Duty: Modern Warfare Modern Warfare Vendor 2"},
        {"odinv3", "Call of Duty: Modern Warfare Modern Warfare Vendor 3"},
        {"odinv4", "Call of Duty: Modern Warfare Modern Warfare Vendor 4"},
        {"odinv5", "Call of Duty: Modern Warfare Modern Warfare Vendor 5"},
        {"odinv6", "Call of Duty: Modern Warfare Modern Warfare Vendor 6"},
        {"odinv7", "Call of Duty: Modern Warfare Modern Warfare Vendor 7"},
        {"odinv8", "Call of Duty: Modern Warfare Modern Warfare Vendor 8"},
        {"odinv9", "Call of Duty: Modern Warfare Modern Warfare Vendor 9"},
        {"lazr", "Call of Duty: MW2 Campaign Remastered"},
        {"lazrdev", "Call of Duty: Modern Warfare (Campaign Remastered) Dev"},
        {"lazrv1", "Call of Duty: MW2 Campaign Remastered Vendor 1"},
        {"lazrv2", "Call of Duty: MW2 Campaign Remastered Vendor 2"},
        {"zeus", "Call of Duty: Black Ops Cold War"},
        {"zeusa", "Call of Duty: Black Ops Cold War Closed Internal Alpha"},
        {"zeusb", "Call of Duty: Black Ops Cold War Beta"},
        {"zeusc", "Call of Duty: Black Ops Cold War CDL Player"},
        {"zeuscdlevent", "Call of Duty: Black Ops Cold War CDL Event"},
        {"zeuscdlstaff", "Call of Duty: Black Ops Cold War CDL Staff"},
        {"zeusdev", "Call of Duty: Black Ops Cold War Development Region"},
        {"zeusevent", "Call of Duty: Black Ops Cold War Event 1"},
        {"zeusr", "Call of Duty: Black Ops Cold War Black Ops Cold War"},
        {"zeusv1", "Call of Duty: Black Ops Cold War Vendor 1"},
        {"zeusv10", "Call of Duty: Black Ops Cold War Vendor 10"},
        {"zeusv11", "Call of Duty: Black Ops Cold War Vendor 11"},
        {"zeusv12", "Call of Duty: Black Ops Cold War Vendor 12"},
        {"zeusv13", "Call of Duty: Black Ops Cold War Vendor 13"},
        {"zeusv14", "Call of Duty: Black Ops Cold War Vendor 14"},
        {"zeusv15", "Call of Duty: Black Ops Cold War Vendor 15"},
        {"zeusv16", "Call of Duty: Black Ops Cold War Vendor 16"},
        {"zeusv2", "Call of Duty: Black Ops Cold War Vendor 2"},
        {"zeusv3", "Call of Duty: Black Ops Cold War Vendor 3"},
        {"zeusv4", "Call of Duty: Black Ops Cold War Vendor 4"},
        {"zeusv5", "Call of Duty: Black Ops Cold War Vendor 5"},
        {"zeusv6", "Call of Duty: Black Ops Cold War Vendor 6"},
        {"zeusv7", "Call of Duty: Black Ops Cold War Vendor 7"},
        {"zeusv8", "Call of Duty: Black Ops Cold War Vendor 8"},
        {"zeusv9", "Call of Duty: Black Ops Cold War Vendor 9"},
        {"viper", "Call of Duty: Black Ops 4"},
        {"viperdev", "Call of Duty: Black Ops 4 Alpha"},
        {"viperv1", "Call of Duty: Black Ops 4 Black Ops 4 Vendor"},
        {"wlby", "Crash Bandicoot 4: It's About Time"},
        {"wlbya", "Crash Bandicoot 4: It's About Time Alpha"},
        {"wlbydev", "Crash Bandicoot 4: It's About Time Crash Development Region"},
        {"wlbyt", "Crash Bandicoot 4: It's About Time Public Test Realm"},
        {"wlbyv1", "Crash Bandicoot 4: It's About Time Crash Bandicoot 4 Vendor 1"},
        {"wlbyv2", "Crash Bandicoot 4: It's About Time Crash Bandicoot 4 Vendor 2"},
        {"wlbyv3", "Crash Bandicoot 4: It's About Time Crash Bandicoot 4 Vendor 3"},
        {"wlbyv4", "Crash Bandicoot 4: It's About Time Crash Bandicoot 4 Vendor 4"},
        {"wlbyv5", "Crash Bandicoot 4: It's About Time Crash Bandicoot 4 Vendor 5"},
        {"wlbyv6", "Crash Bandicoot 4: It's About Time Crash Bandicoot 4 Vendor 6"},
        {"spot", "Spot"},
        {"spotb", "Spot Beta"},
        {"spotdev", "Spot Development Region"},
        {"spotv1", "Spot Vendor 1"},
        {"spotv10", "Spot Vendor 10"},
        {"spotv11", "Spot Vendor 11"},
        {"spotv12", "Spot Vendor 12"},
        {"spotv13", "Spot Vendor 13"},
        {"spotv14", "Spot Vendor 14"},
        {"spotv15", "Spot Vendor 15"},
        {"spotv16", "Spot Vendor 16"},
        {"spotv17", "Spot Vendor 17"},
        {"spotv18", "Spot Vendor 18"},
        {"spotv19", "Spot Vendor 19"},
        {"spotv2", "Spot Vendor 2"},
        {"spotv20", "Spot Vendor 20"},
        {"spotv3", "Spot Vendor 3"},
        {"spotv4", "Spot Vendor 4"},
        {"spotv5", "Spot Vendor 5"},
        {"spotv6", "Spot Vendor 6"},
        {"spotv7", "Spot Vendor 7"},
        {"spotv8", "Spot Vendor 8"},
        {"spotv9", "Spot Vendor 9"},
    };
    string getGameNameByCodeName(string codeName);
    void Init(Napi::Env env, Napi::Object exports);
}